apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: atlantis-secrets
  namespace: atlantis
spec:
  serviceAccountName: default
  target:
    name: atlantis-secrets
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: StatefulSet
      name: atlantis
  secrets:
    ATLANTIS_GH_APP_ID: atlantis-prod.gh_app_id
    ATLANTIS_GH_APP_KEY: atlantis-prod.gh_app_key
    ATLANTIS_GH_WEBHOOK_SECRET: atlantis-prod.gh_webhook_secret
    ATLANTIS_WEB_PASSWORD: atlantis-prod.web_password
    AWS_ACCESS_KEY_ID: atlantis-prod.aws_access_key_id
    AWS_SECRET_ACCESS_KEY: atlantis-prod.aws_secret_access_key
    CLOUDFLARE_API_TOKEN: atlantis-prod.cloudflare_api_token
