apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: ghcr.io/gaucho-racing/sentinel-core:latest
          ports:
            - containerPort: 9999
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: sentinel-secrets
          env:
            - name: ENV
              value: PROD
            - name: PORT
              value: "9999"
            - name: DATABASE_NAME
              value: sentinel
            - name: DATABASE_HOST
              value: postgres.sentinel.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: sentinel
spec:
  selector:
    app: core
  ports:
    - port: 9999
      targetPort: 9999
