apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: sentinel-github-secrets
  namespace: sentinel
spec:
  serviceAccountName: default
  target:
    name: sentinel-github-secrets
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: Deployment
      name: github
  secrets:
    GITHUB_CLIENT_ID: sentinel-prod.github_client_id
    GITHUB_APP_ID: sentinel-prod.github_app_id
    GITHUB_CLIENT_SECRET: sentinel-prod.github_client_secret
    GITHUB_APP_PRIVATE_KEY: sentinel-prod.github_app_private_key
    GITHUB_INSTALLATION_ID: sentinel-prod.github_installation_id
