apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
  namespace: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
        - name: oauth
          image: ghcr.io/gaucho-racing/sentinel-oauth:latest
          ports:
            - containerPort: 9997
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: sentinel-secrets
          env:
            - name: ENV
              value: PROD
            - name: PORT
              value: "9997"
            - name: DATABASE_NAME
              value: sentinel
            - name: DATABASE_HOST
              value: postgres.sentinel.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: oauth
  namespace: sentinel
spec:
  selector:
    app: oauth
  ports:
    - port: 9997
      targetPort: 9997
