apiVersion: apps/v1
kind: Deployment
metadata:
  name: saml
  namespace: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saml
  template:
    metadata:
      labels:
        app: saml
    spec:
      containers:
        - name: saml
          image: ghcr.io/gaucho-racing/sentinel-saml:latest
          ports:
            - containerPort: 9996
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: sentinel-secrets
          env:
            - name: ENV
              value: PROD
            - name: PORT
              value: "9996"
            - name: DATABASE_NAME
              value: sentinel
            - name: DATABASE_HOST
              value: postgres.sentinel.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: saml
  namespace: sentinel
spec:
  selector:
    app: saml
  ports:
    - port: 9996
      targetPort: 9996
