apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: sentinel-secrets
  namespace: sentinel
spec:
  serviceAccountName: default
  target:
    name: sentinel-secrets
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: Deployment
      name: core
    - kind: Deployment
      name: oauth
    - kind: Deployment
      name: discord
    - kind: Deployment
      name: saml
    - kind: Deployment
      name: google
    - kind: Deployment
      name: kerbecs
  secrets:
    DATABASE_HOST: gr-postgres.database_host
    DATABASE_PORT: gr-postgres.database_port
    DATABASE_USER: gr-postgres.database_user
    DATABASE_PASSWORD: gr-postgres.database_password
    INTERNAL_BOOTSTRAP_SECRET: sentinel-prod.internal_bootstrap_secret
    KERBECS_PASSWORD: sentinel-prod.kerbecs_password
    DISCORD_TOKEN: sentinel-prod.discord_token
    DISCORD_CLIENT_SECRET: sentinel-prod.discord_client_secret
    GOOGLE_SERVICE_ACCOUNT: sentinel-prod.google_service_account
    ISSUER: sentinel-prod.issuer
    KERBECS_ENDPOINT: sentinel-prod.kerbecs_endpoint
    KERBECS_USER: sentinel-prod.kerbecs_user
    DISCORD_CLIENT_ID: sentinel-prod.discord_client_id
    DISCORD_REDIRECT_URI: sentinel-prod.discord_redirect_uri
    DISCORD_GUILD: sentinel-prod.discord_guild
    DISCORD_PREFIX: sentinel-prod.discord_prefix
    WEB_BASE_URL: sentinel-prod.web_base_url
    TEAM_GOOGLE_CLIENT_ID: sentinel-prod.team_google_client_id
    GOOGLE_ADMIN_SUBJECT: sentinel-prod.google_admin_subject
