apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: external-dns-secrets
  namespace: external-dns
spec:
  serviceAccountName: default
  target:
    name: cloudflare-api-token
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: Deployment
      name: external-dns
  secrets:
    api-token: cloudflare-prod.api_token
