apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord
  namespace: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord
  template:
    metadata:
      labels:
        app: discord
    spec:
      containers:
        - name: discord
          image: ghcr.io/gaucho-racing/sentinel-discord:5.1.0
          ports:
            - containerPort: 9998
          env:
            - name: ENV
              value: PROD
            - name: PORT
              value: "9998"
            - name: DATABASE_HOST
              value: postgres.sentinel.svc.cluster.local
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_NAME
              value: sentinel
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentinel-secrets
                  key: POSTGRES_PASSWORD
            - name: RINCON_ENDPOINT
              value: http://rincon.sentinel.svc.cluster.local:10311
            - name: RINCON_USER
              value: admin
            - name: RINCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentinel-secrets
                  key: RINCON_PASSWORD
            - name: SERVICE_ENDPOINT
              value: http://discord.sentinel.svc.cluster.local:9998
            - name: SERVICE_HEALTH_CHECK
              value: http://discord.sentinel.svc.cluster.local:9998/discord/ping
            - name: DISCORD_GUILD
              value: "756738476887638107"
            - name: DISCORD_PREFIX
              value: "d!"
            - name: WEB_BASE_URL
              value: https://sentinel-v5.gauchoracing.com
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sentinel-secrets
                  key: DISCORD_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: discord
  namespace: sentinel
spec:
  selector:
    app: discord
  ports:
    - port: 9998
      targetPort: 9998
