apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
  namespace: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
        - name: oauth
          image: ghcr.io/gaucho-racing/sentinel-oauth:latest
          ports:
            - containerPort: 9997
          env:
            - name: ENV
              value: PROD
            - name: PORT
              value: "9997"
            - name: DATABASE_HOST
              value: gr-postgres.gauchoracing.com
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_NAME
              value: sentinel
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentinel-secrets
                  key: POSTGRES_PASSWORD
            - name: RINCON_ENDPOINT
              value: http://rincon:10311
            - name: RINCON_USER
              value: admin
            - name: RINCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentinel-secrets
                  key: RINCON_PASSWORD
            - name: SERVICE_ENDPOINT
              value: http://oauth:9997
            - name: SERVICE_HEALTH_CHECK
              value: http://oauth:9997/oauth/ping
---
apiVersion: v1
kind: Service
metadata:
  name: oauth
  namespace: sentinel
spec:
  selector:
    app: oauth
  ports:
    - port: 9997
      targetPort: 9997
