apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: mapache-secrets
  namespace: mapache
spec:
  serviceAccountName: default
  target:
    name: mapache-secrets
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: Deployment
      name: kerbecs
    - kind: Deployment
      name: auth
    - kind: Deployment
      name: vehicle
    - kind: Deployment
      name: gr26
    - kind: Deployment
      name: live
    - kind: Deployment
      name: query
    - kind: Deployment
      name: foreman
  secrets:
    DATABASE_PASSWORD: gr-postgres.database_password
    CLICKHOUSE_PASSWORD: mapache-prod.clickhouse_password
    KERBECS_PASSWORD: mapache-prod.kerbecs_password
    MQTT_USER: mapache-prod.mqtt_user
    MQTT_PASSWORD: mapache-prod.mqtt_password
    SENTINEL_CLIENT_SECRET: mapache-prod.sentinel_client_secret
    SENTINEL_SA_TOKEN: mapache-prod.sentinel_sa_token
    AWS_ACCESS_KEY_ID: mapache-prod.aws_access_key_id
    AWS_SECRET_ACCESS_KEY: mapache-prod.aws_secret_access_key
