apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: bifrost-secrets
  namespace: bifrost
spec:
  serviceAccountName: default
  target:
    name: bifrost-secrets
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: StatefulSet
      name: bifrost
  secrets:
    encryption-key: bifrost-prod.encryption_key
    username: bifrost-prod.admin_username
    password: bifrost-prod.admin_password
