apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: depot-secrets
  namespace: depot
spec:
  serviceAccountName: default
  target:
    name: depot-secrets
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: Deployment
      name: depot
    - kind: Deployment
      name: kerbecs
  secrets:
    DATABASE_PASSWORD: postgres-prod.password
    DATABASE_USER: postgres-prod.username
    KERBECS_PASSWORD: depot-prod.kerbecs_password
    SENTINEL_CLIENT_SECRET: depot-prod.sentinel_client_secret
    SENTINEL_SA_TOKEN: depot-prod.sentinel_sa_token
