apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: jiffy-secrets
  namespace: jiffy
spec:
  serviceAccountName: default
  target:
    name: jiffy-secrets
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: Deployment
      name: api
  secrets:
    DATABASE_PASSWORD: gr-postgres.database_password
    SENTINEL_CLIENT_SECRET: jiffy-prod.sentinel_client_secret
    SENTINEL_TOKEN: jiffy-prod.sentinel_token
    S3_ACCESS_KEY: jiffy-prod.s3_access_key
    S3_SECRET_KEY: jiffy-prod.s3_secret_key
    DRIVE_SERVICE_ACCOUNT: jiffy-prod.drive_service_account
