apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: workbench-secrets
  namespace: workbench
spec:
  serviceAccountName: default
  target:
    name: workbench-secrets
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: Deployment
      name: workbench
    - kind: Deployment
      name: kerbecs
  secrets:
    DATABASE_PASSWORD: postgres-prod.password
    DATABASE_USER: postgres-prod.username
    KERBECS_PASSWORD: workbench-prod.kerbecs_password
    SENTINEL_CLIENT_SECRET: workbench-prod.sentinel_client_secret
    TARGET_ENCRYPTION_KEY: workbench-prod.target_encryption_key
