apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Gaucho-Racing/infrastructure.git
    targetRevision: main
    path: kubernetes/gr-foundry/manifests/sentinel
  destination:
    server: https://kubernetes.default.svc
    namespace: sentinel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
