apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: postgres-prod-secrets
  namespace: postgres-prod
spec:
  serviceAccountName: default
  target:
    name: postgres-prod-secrets
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: StatefulSet
      name: postgres-prod
  secrets:
    POSTGRES_DB: postgres-prod.database
    POSTGRES_PASSWORD: postgres-prod.password
    POSTGRES_USER: postgres-prod.username
