apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: postgres-secrets
  namespace: postgres
spec:
  serviceAccountName: default
  target:
    name: postgres-secrets
    type: Opaque
  refreshInterval: 5m
  rolloutTargets:
    - kind: StatefulSet
      name: postgres
  secrets:
    POSTGRES_PASSWORD: gr-postgres.database_password
