variable "name" {
  description = "Friendly name for the NanoMQ instance. Used in resource Name tags + SG name."
  type        = string
}

variable "vpc_id" {
  description = "VPC the EC2 lives in. Should be the same VPC as EKS so pods reach it via private IP."
  type        = string
}

variable "subnet_id" {
  description = "Subnet to launch into. Pick a public subnet if associate_public_ip = true."
  type        = string
}

variable "availability_zone" {
  description = "AZ for the instance. Must match the AZ of the chosen subnet."
  type        = string
}

variable "instance_type" {
  description = "EC2 instance type. t4g.small (2GB RAM, ARM) is comfortable for NanoMQ at expected throughput."
  type        = string
  default     = "t4g.small"
}

variable "nanomq_version" {
  description = "Pinned NanoMQ image tag. Matches the version running on-car (TCM-26) so behavior is identical on both ends of the pipe."
  type        = string
  default     = "0.24.13"
}

variable "mqtt_user" {
  description = "MQTT username configured in nanomq.conf. The random password generated by the module is paired with this user."
  type        = string
  default     = "gr26"
}

variable "allowed_security_group_ids" {
  description = "Security group IDs allowed to connect on port 1883. Typically the EKS node SG."
  type        = list(string)
  default     = []
}

variable "admin_cidr_blocks" {
  description = "CIDR blocks allowed to connect to 1883 directly. The on-car TCM publishes from arbitrary cellular IPs, so usually \"0.0.0.0/0\" + password is the model."
  type        = list(string)
  default     = []
}

variable "associate_public_ip" {
  description = "If true, the instance gets a public IP via an EIP. Required when allowing inbound connections from outside the VPC (e.g. the on-car TCM)."
  type        = bool
  default     = false
}
